name: inflector_dart
description: "A lightweight Dart utility for smart word transformations - from singular to plural, snake_case to camelCase, and everything in between."
version: 1.0.1
homepage: https://github.com/didanurwanda/inflector-dart
repository: https://github.com/didanurwanda/inflector-dart
license: MIT

topics:
  - camelcase
  - snakecase
  - string
  - inflector
  - text-processing

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: {}

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
