name: Dart CI/CD

on:
  push:
    branches:
      - master
    tags:
      - "v*" # hanya tag yang dimulai dengan "v" misal v1.0.0
  pull_request:

jobs:
  test:
    name: Run Tests & Debug
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Analyze code
        run: dart analyze

      - name: Run tests
        run: dart test

  publish:
    name: Publish to pub.dev
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v') # hanya jika push tag

    steps:
      - uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Publish package
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}
        run: dart pub publish --force
