name: Dart CI/CD

on:
  push:
    branches:
      - master
    tags:
      - "v*" # trigger workflow untuk publish hanya pada tag yang dimulai dengan 'v'
  pull_request:

jobs:
  test:
    name: Run Tests & Debug
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Analyze code
        run: dart analyze

      - name: Run tests
        run: dart test

  publish:
    permissions:
      id-token: write # Required for authentication using OIDC

    name: Publish to pub.dev
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v') # hanya untuk tag yang dimulai dengan 'v'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Publish package
        run: dart pub publish --force
